### PR TITLE
Metadata merge

### PR DESCRIPTION
**Pull request by bmiller**

### CODE REVIEW

**Comment by Mobe1969** [comment]
This does seem to have updated the PEQ sections also in the few I've checked. On the bypass ones no issue, but the hex etc look different on active ones. How are they generated?
image

**Comment by bmiller** [comment]
Yeah, my app rewrites the entire file since it's also for creating new BEQ files.  The dec and hex are generated in app using the the same algorithm as BEQd.  My generation has matched up with d00d's on every one I've checked and usually matches was in the file created by the plugin.  

The ones the existing file in your screen shot looks like the old format that that was giving me an issue with resaving inside the plugin that we talked about like a month ago.  For all of the ones that that happened to I checked against the merge output from BEQd and mine matched its.  It looks like the plugin was doing something different than it is now when we first started BEQ.

**Comment by Mobe1969** [comment]
OK cool.

Regards future updates I do to them, I take it I'll need to merge the metadata in manually?

I'll try to figure how to get a decent git too to do this. Eg say I change a filter and save it in BEQD and it loses metadata, then when I look at changes I can use say winmerge to copy the metadata section back over

**Comment by bmiller** [comment]
Yeah, if you update an existing file you'd need to do that.  For new files you can copy over the metadata block and then edit.  If I get some spare time I'll see if I can update the post builder in BEQd to do the new fields and pull the data from TMDB.  It has a generate file feature so you'd be able to use it for everything and bypass the plugin when you create a new BEQ.  I'm not sure how quick I'll be able to get to it though.  I have to brush up my python skills too.  :)

**Comment by Mobe1969** [comment]
Nice. Yeah too many of these languages (or worse the dev environments) are just too much for me to pick up without too much dedicated time...

As a dev I'm too old school. I don't honestly like git and prefer how it is in the microsoft TFS/VSO as just easier to integrate in the  IDE. All these git things are piecemeal and a few hundred ways of doing the same thing, and nothing well integrated.

**Comment by bmiller** [comment]
Yeah the ides are the biggest issue. If I could use Xcode over PyCharm for it I'd be happy.  Not that Xcode is the greatest but because it's what I'm used from working in it all day.  Languages are usually pretty easy to pick up since they all mostly center around C like syntax.  

I resisted git at first too but that that I'm used to it, it's great.  It's mainly getting over the learning curve of how it works.  I was mostly SVN and CVS before it.  A good client really helps.  SourceTree is my current favorite since it does everything and is free.  I've found most clients, like the github one, don't have enough features and hamstring you too much.  There's a couple other full feature ones like gitkracken but I have trouble shelling out $50/year when it does the same job for me as SourceTree.

**Comment by Mobe1969** [comment]
Ah nice sourcetree, I'll try that!

**Comment by Mobe1969** [comment]
I'm just trying simulating an update (just a straight open /  save) with the latest BEQD, and I'm still seeing numbers generated that difffer to what your generated ones (hex, etc as well as the bypassed ones q 0.9 / 0.7

image

**Comment by bmiller** [comment]
Where is the right side coming from?  Is that a BEQD save, plugin, or something else?  I just created a test file with 31hz, 7.0 boost, .8q Low shelf and go the following that matches the right.  It's with the 1.15.0 version of the plugin.  The bypassed ones are the same too.  the number of digits shown doesn't matter for zero.  It reads and writes them the same.  

`<filter name="PEQ_1_10" addr="8325">
    <freq>31</freq>
    <q>0.8</q>
    <boost>7</boost>
    <type>SL</type>
    <bypass>0</bypass>
    <dec>1.000514762445383,-1.9979243103321147,0.9974157009397989,1.9979260126247251,-0.9979287610925719,</dec>
    <hex>3f8010de,bfffbbfc,3f7f56a3,3fffbc0a,bf7f7842,</hex>
  </filter>`

**Comment by Mobe1969** [comment]
I loaded your filter into beqd, latest version, and saved it. These are the differences. Ford the bypassed ones fine, but the non bypassed hex codes different too.

**Comment by bmiller** [comment]
It looks like there's a bug in BEQd that you're seeing.  I'm guessing the export is using the wrong device type.  I'd have to check the code though to know for sure.  I just loaded and saved 7 Below and it has different dec and hex values from the file produced by merge.  The merge file has the same values as mine and what the 2x4 HD plugin shows.

**Comment by Mobe1969** [comment]
Ah gee. Ugh. Any idea how I can get BEQD to save them properly? Or some way to fix any future ones? I guess all the ones I merged from you yesterday are then corrected then.

**Comment by bmiller** [comment]
yeah, everything from yesterday is correct.  I'm loading up the BEQd project now to see if I can see an easy fix.  I hadn't pulled in awhile so I had to update first.  

I'm honestly not sure how much of an issue it is.  I think just about everyone merges before use which will fix them.  I'm also not clear if the plugin actually uses the values. Sometimes it seems to load the values and recalculated the dec and hex.  But even if that's the case we need to fix BEQd.

**Comment by Mobe1969** [comment]
Yeah, it is annoying how some stuff is just unknown - namely the plugin reflects either that you are in standard mode or the advanced mode for the filters, but there doesn't seem to be some flag in the XML to indicate it is one or the other.

**Comment by bmiller** [comment]
Ok, I figured out what's going on.  The biquads aren't being recalculated on export with the proper fs value.  He has an internal one that's being used instead of the correct one for the device.  I'm going to send Matt a bug report on it because I'm not sure what's the cleanest way to fix it that might not have side effect.

**Comment by Mobe1969** [comment]
Thanks Brad!

**Comment by bmiller** [comment]
no problem.  It was a confusing one when I was stepping through it in the debugger.  Finally caught the math issue.  10/1000 is a bit different than 10/96000 :)

**Pull request merged**
