### PR TITLE
Fixed that catalogue parsing issue

### PR DESCRIPTION
**Pull request by bmiller**

### CODE REVIEW

**Comment by Mobe1969** [comment]
Do you know what the parsing issue was, and what specific file / files? It'd be good to understand. The build log didn't even show a file name.

**Comment by Mobe1969** [comment]
Ah I see the "/ >" for the empty tag...

**Comment by bmiller** [comment]
yeah, I fat fingered the space and did "/ >" instead of " />"

**Comment by Mobe1969** [comment]
Yeah I'm unsure why none of the editors I opened them in complained about it being malformed.

**Pull request merged**
